version: '3'

services:
  app:
    image: ghcr.io/gardo32/data-cosmos:latest
    platform: ${DOCKER_PLATFORM:-linux/amd64}
    ports:
      - "5000:5000"
    volumes:
      - ./data:/data
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - FLASK_APP=app.py
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1